### ISSUE TITLE
gulp build is broken

### ISSUE THREAD

**Issue by Kudrik** [jl-/react-slide-deck#7]
gulp build
[14:22:45] Requiring external module babel-register
/Users/kudrik/RubymineProjects/test/react-slide-deck/node_modules/babel-register/node_modules/babel-core/lib/transformation/file/logger.js:41
    throw new Constructor(this._buildMessage(msg));
    ^

ReferenceError: [BABEL] /Users/kudrik/RubymineProjects/test/react-slide-deck/gulpfile.babel.js: Unknown option: base.stage
    at Logger.error (/Users/kudrik/RubymineProjects/test/react-slide-deck/node_modules/babel-register/node_modules/babel-core/lib/transformation/file/logger.js:41:11)
    at OptionManager.mergeOptions (/Users/kudrik/RubymineProjects/test/react-slide-deck/node_modules/babel-register/node_modules/babel-core/lib/transformation/file/options/option-manager.js:289:18)
    at OptionManager.init (/Users/kudrik/RubymineProjects/test/react-slide-deck/node_modules/babel-register/node_modules/babel-core/lib/transformation/file/options/option-manager.js:486:10)
    at File.initOptions (/Users/kudrik/RubymineProjects/test/react-slide-deck/node_modules/babel-register/node_modules/babel-core/lib/transformation/file/index.js:211:75)
    at new File (/Users/kudrik/RubymineProjects/test/react-slide-deck/node_modules/babel-register/node_modules/babel-core/lib/transformation/file/index.js:129:22)
    at Pipeline.transform (/Users/kudrik/RubymineProjects/test/react-slide-deck/node_modules/babel-register/node_modules/babel-core/lib/transformation/pipeline.js:48:16)
    at Object.transformFileSync (/Users/kudrik/RubymineProjects/test/react-slide-deck/node_modules/babel-register/node_modules/babel-core/lib/api/node.js:118:10)
    at compile (/Users/kudrik/RubymineProjects/test/react-slide-deck/node_modules/babel-register/lib/node.js:100:20)
    at loader (/Users/kudrik/RubymineProjects/test/react-slide-deck/node_modules/babel-register/lib/node.js:128:14)
    at Object.require.extensions.(anonymous function) [as .js](/Users/kudrik/RubymineProjects/test/react-slide-deck/node_modules/babel-register/lib/node.js:138:7)

**Comment by jl-** [comment]
Maybe it's a babel-related problem. It works fine here with node v5.1.0 & babel 5.x & gulp 3.9. And I just push a new commit to update babel to 6.x, would you mind fetching the new setup updates and give it another shot?

**Comment by Kudrik** [comment]
Now it is **fixed**
